spring:
  application:
   name: jpa_one_to_many
  datasource:
    url: jdbc:mysql://localhost:13306/jpa_test
    username: ${DB_U}
    password: ${DB_P}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
